@host=http://localhost:8080

### Health Check
GET {{host}}/health
Content-Type: application/json

### Get Categories
GET {{host}}/api/v1/categories?page=1&size=100
Content-Type: application/json

### Get Category
GET {{host}}/api/v1/categories/17e938c6-14c3-412f-bc87-446092d7c073
Content-Type: application/json

### Create Category
POST {{host}}/api/v1/categories
Content-Type: application/json

{
    "title": "category",
    "description": "category description"
}

### Delete Category
DELETE {{host}}/api/v1/categories/855dedf1-825e-44e0-afe4-25d6668d9a25
Content-Type: application/json