apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product-catalog
  namespace: ns-products
  labels:
    fargate: "true"
    app: ms-product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      fargate: "true"
      app: ms-product-catalog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        fargate: "true"
        app: ms-product-catalog
    spec:
      serviceAccountName: sa-products
      containers:
        - name: ms-product-catalog
          image: jsfelipearaujo/ms-product-catalog:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 4
            successThreshold: 1
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: ms-product-catalog-config
          # env:
          #   - name: DB_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: database-url
          #         key: url
          # volumeMounts:
          #   - name: secrets-store-inline
          #     mountPath: "/mnt/secrets-store"
          #     readOnly: true
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      tolerations: []
      # volumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "aws-secrets"
