apiVersion: v1
kind: Service
metadata:
  name: ms-product-catalog
  namespace: ns-products
  labels:
    app: ms-product-catalog
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ms-product-catalog
