// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/jfelipearaujo-org/ms-product-catalog/internal/entity"
	create_category "github.com/jfelipearaujo-org/ms-product-catalog/internal/service/category/create_category"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateCategoryService is an autogenerated mock type for the CreateCategoryService type
type MockCreateCategoryService struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, request
func (_m *MockCreateCategoryService) Handle(ctx context.Context, request create_category.CreateCategoryDto) (*entity.Category, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, create_category.CreateCategoryDto) (*entity.Category, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, create_category.CreateCategoryDto) *entity.Category); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, create_category.CreateCategoryDto) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCreateCategoryService creates a new instance of MockCreateCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCategoryService {
	mock := &MockCreateCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
