// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/jfelipearaujo-org/ms-product-catalog/internal/entity"
	create_product "github.com/jfelipearaujo-org/ms-product-catalog/internal/service/product/create_product"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateProductService is an autogenerated mock type for the CreateProductService type
type MockCreateProductService struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, request
func (_m *MockCreateProductService) Handle(ctx context.Context, request create_product.CreateProductDto) (*entity.Product, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, create_product.CreateProductDto) (*entity.Product, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, create_product.CreateProductDto) *entity.Product); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, create_product.CreateProductDto) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCreateProductService creates a new instance of MockCreateProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateProductService {
	mock := &MockCreateProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
