// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/jfelipearaujo-org/ms-product-catalog/internal/common"

	entity "github.com/jfelipearaujo-org/ms-product-catalog/internal/entity"

	get_categories "github.com/jfelipearaujo-org/ms-product-catalog/internal/service/category/get_categories"

	mock "github.com/stretchr/testify/mock"
)

// MockGetCategoriesService is an autogenerated mock type for the GetCategoriesService type
type MockGetCategoriesService struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, pagination, request
func (_m *MockGetCategoriesService) Handle(ctx context.Context, pagination common.Pagination, request get_categories.GetCategoriesDto) (int64, []entity.Category, error) {
	ret := _m.Called(ctx, pagination, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 int64
	var r1 []entity.Category
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Pagination, get_categories.GetCategoriesDto) (int64, []entity.Category, error)); ok {
		return rf(ctx, pagination, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Pagination, get_categories.GetCategoriesDto) int64); ok {
		r0 = rf(ctx, pagination, request)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Pagination, get_categories.GetCategoriesDto) []entity.Category); ok {
		r1 = rf(ctx, pagination, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.Pagination, get_categories.GetCategoriesDto) error); ok {
		r2 = rf(ctx, pagination, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockGetCategoriesService creates a new instance of MockGetCategoriesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCategoriesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCategoriesService {
	mock := &MockGetCategoriesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
