// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/jfelipearaujo-org/ms-product-catalog/internal/entity"
	get_product "github.com/jfelipearaujo-org/ms-product-catalog/internal/service/product/get_product"

	mock "github.com/stretchr/testify/mock"
)

// MockGetProductService is an autogenerated mock type for the GetProductService type
type MockGetProductService struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, request
func (_m *MockGetProductService) Handle(ctx context.Context, request get_product.GetProductDto) (entity.Product, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, get_product.GetProductDto) (entity.Product, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, get_product.GetProductDto) entity.Product); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, get_product.GetProductDto) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGetProductService creates a new instance of MockGetProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetProductService {
	mock := &MockGetProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
